name: Cowsay Time

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  cowsay:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up cowsay
        run: |
          sudo apt-get update
          sudo apt-get install -y cowsay lolcat fortune

      - name: Get current time
        id: time
        run: echo "::set-output name=now::$(date +'%Y-%m-%d %H:%M:%S')"

      - name: Cowsay the time
        run: |
          cowsay "$(fortune) The current time is ${{ steps.time.outputs.now }}" -f $(shuf -e $(ls /usr/share/cowsay/) | head -n 1) | lolcat
